export const JUISIEST = [
    {
        title: 'Кнели со спагетти',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/kneli.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '152',
        saved: '85',
        recomendation: false,
        recName: '',
        recImg: '',
    },
    {
        title: 'Пряная ветчина по итальянски',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/ham.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '257',
        saved: '159',
        recomendation: true,
        recName: 'Елена Высоцкая',
        recImg: '/src/assets/Elena.svg',
    },
    {
        title: 'Лапша с курицей и шафраном',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/shafran.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '342',
        saved: '258',
        recomendation: true,
        recName: 'Alex Cook',
        recImg: '/src/assets/Alex.svg',
    },
    {
        title: 'Том-ям с капустой кимчи',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/tomYam.png',
        group: 'Национальные',
        groupIcon: '/src/assets/national.svg',
        likes: '324',
        saved: '124',
        recomendation: false,
        recName: '',
        recImg: '',
    },
];

export const JUISIESTPAGE = [
    {
        title: 'Лапша с курицей и шафраном',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/shafran.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '342',
        saved: '258',
        recomendation: true,
        recName: 'Alex Cook',
        recImg: '/src/assets/Alex.svg',
    },
    {
        title: 'Том-ям с капустой кимчи',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/tomYam.png',
        group: 'Национальные',
        groupIcon: '/src/assets/national.svg',
        likes: '324',
        saved: '124',
        recomendation: false,
        recName: '',
        recImg: '',
    },
    {
        title: 'Пряная ветчина по итальянски',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/ham.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '257',
        saved: '159',
        recomendation: true,
        recName: 'Елена Высоцкая',
        recImg: '/src/assets/Elena.svg',
    },
    {
        title: 'Кнели со спагетти',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/kneli.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '180',
        saved: '120',
        recomendation: false,
        recName: '',
        recImg: '',
    },
    {
        title: 'Картошка, тушенная с болгарским перцем и фасолью в томатном соусе',
        text: 'Картошка, тушенная с болгарским перцем, фасолью, морковью и луком, -  вариант сытного блюда на каждый день. Фасоль в данном случае заменяет  мясо, делая рагу сытным и питательным. Чтобы сократить время  приготовления, возьмём консервированную фасоль. Блюдо хоть и простое, но в полной мере наполнено ароматами и имеет выразительный вкус за счёт  добавления томатной пасты.',
        image: '/src/assets/potato.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '180',
        saved: '120',
        recomendation: false,
        recName: '',
        recImg: '',
    },
    {
        title: 'Картофельные рулетики с грибами',
        text: 'Рекомендую всем приготовить постное блюдо из картофеля и грибов.  Готовится это блюдо без яиц, без мяса и без сыра, из самых простых  ингредиентов, а получается очень вкусно и сытно. Постный рецепт  картофельных рулетиков с грибами, в томатном соусе, - на обед, ужин и  даже на праздничный стол!',
        image: '/src/assets/rulets.png',
        group: 'Детские блюда',
        groupIcon: '/src/assets/kid.svg',
        likes: '180',
        saved: '85',
        recomendation: false,
        recName: '',
        recImg: '',
    },
    {
        title: 'Овощная лазанья из лаваша',
        text: 'Большое, сытное блюдо для ценителей блюд без мяса! Такая лазанья  готовится с овощным соусом и соусом бешамель, а вместо листов для  лазаньи используется тонкий лаваш.',
        image: '/src/assets/lazagnia.png',
        group: 'Блюда на гриле',
        groupIcon: '/src/assets/grill.svg',
        likes: '152',
        saved: '85',
        recomendation: false,
        recName: '',
        recImg: '',
    },
    {
        title: 'Тефтели из булгура и чечевицы, запечённые в томатном соусе',
        text: 'Тефтели из булгура и чечевицы – яркие и питательные, отлично подходят  для постного и вегетарианского меню. Тефтели получаются нежными, а также сочными и ароматными благодаря использованию томатного соуса и душистых пряностей.',
        image: '/src/assets/meatballs.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '150',
        saved: '85',
        recomendation: false,
        recName: '',
        recImg: '',
    },
];
