export const JUISIEST = [
    {
        title: 'Кнели со спагетти',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/kneli.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '152',
        saved: '85',
        recomendation: false,
        recName: '',
        recImg: '',
    },
    {
        title: 'Пряная ветчина по итальянски',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/ham.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '257',
        saved: '159',
        recomendation: true,
        recName: 'Елена Высоцкая',
        recImg: '/src/assets/Elena.png',
    },
    {
        title: 'Лапша с курицей и шафраном',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/shafran.png',
        group: 'Вторые блюда',
        groupIcon: '/src/assets/pan.svg',
        likes: '342',
        saved: '258',
        recomendation: true,
        recName: 'Alex Cook',
        recImg: '/src/assets/Alex.png',
    },
    {
        title: 'Том-ям с капустой кимчи',
        text: 'Как раз после праздников, когда мясные продукты еще остались, но никто их уже не хочет, время варить солянку.',
        image: '/src/assets/tomYam.png',
        group: 'Национальные',
        groupIcon: '/src/assets/national.svg',
        likes: '324',
        saved: '124',
        recomendation: false,
        recName: '',
        recImg: '',
    },
];
